# Generated by Django 4.2.6 on 2023-11-21 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_tag_recipe_count_alter_tag_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='recipe_count',
            field=models.IntegerField(default=0),
        ),
    ]
