# Generated by Django 4.2.6 on 2023-11-22 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0003_alter_tag_recipe_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='recipe_count',
        ),
    ]
