# Generated by Django 4.2.6 on 2023-11-06 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(error_messages={'unique': 'User With This Email Is Already Registered'}, max_length=255, unique=True),
        ),
    ]
