# Generated by Django 4.2.6 on 2023-11-07 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_options_customuser_date_joined'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='competence_level',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Not chosen'), (1, 'Novice'), (2, 'Intermediate'), (3, 'Proficient'), (4, 'Advanced'), (5, 'Expert')], default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='username',
            field=models.CharField(default=1, max_length=38, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customuser',
            name='first_name',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='last_name',
            field=models.CharField(max_length=32),
        ),
    ]
