# Generated by Django 4.2.6 on 2023-12-20 11:20

import apps.users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_competence_level_customuser_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(default=123, upload_to=apps.users.models.profile_picture_file_path),
            preserve_default=False,
        ),
    ]
