# Generated by Django 4.2.6 on 2023-12-18 07:21

import apps.recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_recipe_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(null=True, upload_to=apps.recipes.models.recipe_image_file_path),
        ),
    ]
