# Generated by Django 4.2.6 on 2023-12-18 13:53

import apps.recipes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_remove_recipe_image_recipeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='image',
            field=models.ImageField(default=123, upload_to=apps.recipes.models.recipe_image_file_path),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RecipeImage',
        ),
    ]
