---
name: Checks

on: [ push ]

jobs:
  test-lint:
    name: Test and lint
    runs-on: ubuntu-20.04
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v2
      - name: 'Create env file'
        run: |
          echo "POSTGRES_USER='${{ secrets.POSTGRES_USER }}'" > .env
          echo "POSTGRES_DB_NAME='${{ secrets.POSTGRES_DB_NAME }}'" >> .env
          echo "POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}'" >> .env
          echo "POSTGRES_HOST='${{ secrets.POSTGRES_HOST }}'" >> .env
          echo "POSTGRES_PORT='${{ secrets.POSTGRES_PORT }}'" >> .env
          echo "SECRET_KEY='${{ secrets.SECRET_KEY }}'" >> .env
          echo "DEBUG_VALUE='${{ secrets.DEBUG_VALUE }}'" >> .env
      - name: Test
        run: |
          echo "run db"
          docker-compose up db
          echo "run web_api"
          docker-compose up web_api
          docker-compose exec web_api sh -c "python application/manage.py test"
      - name: Lint
        run: |
          echo "run db"
          docker-compose run db
          echo "run web_api"
          docker-compose run web_api
          docker-compose exec web_api sh -c "flake8 application/"